hpcperfstats/site/hpcperfstats_site/urls.py
from django.conf.urls import include
from django.urls import path
from django.views.static import serve
from hpcperfstats.site.hpcperfstats_site import settings
from django.contrib import admin
from hpcperfstats.site.machine.views import home
from hpcperfstats.site.machine import urls

admin.autodiscover()
urlpatterns = [
    path(r'', home, name="dates"),
    path(r'machine/', include(urls, namespace = "machine"), name = "machine"),
    path(r'media/<path>', serve, {'document_root': settings.MEDIA_ROOT}, name = "media"),                       
]

#try:
#from hpcperfstats.site.machine.agave_auth import login, logout, login_oauth, agave_oauth_callback, login_prompt
#print("starting TACC Stats with agave authentication")
#urlpatterns += [
#    path(r'login/', login_oauth, name='login'),
#path(r'login_prompt', login_prompt, name='login_prompt'),
#    path(r'logout/', logout, name='logout'),
#    path(r'agave_oauth_callback/', agave_oauth_callback, name='agave_oauth_callback')    
#]
#except: 
#    pass

hpcperfstats/site/machine/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import DetailView, ListView
from hpcperfstats.site.machine.models import job_data
from hpcperfstats.site.machine.views import *

app_name = "hpcperfstats"

urlpatterns = [
                       path(r'', home, name='dates'),
                       path(r'job/<pk>/',
                           job_dataDetailView.as_view(), name='job_data'),
                       path(r'host/<host>/', host_detail, name='host_view'),
                       path(r'date/<end_time__date>', index, name='date_view'),
                       path(r'username/<username>/', index, name = 'username_view'),
                       path(r'account/<account>/'  , index, name = 'account_view'),
                       path(r'job/<jid>/<type_name>/', type_detail, name = 'type_detail'),
                       #path(r'proc/<pk>/<proc_name>/', proc_detail, name = 'proc_detail'),
                       #path(r'exe/<exe__icontains>)/', index, name='exe_view'),                       
                       path(r'search/',search, name='search'),
]

hpcperfstats/site/machine/models.py
"""The database models of tacc stats"""

from django.db import models
from django.contrib.postgres.fields import ArrayField

class RealField(models.FloatField):
    # Make type in order to use 32 bit floats (reals) instead of 64 bit floats
    def db_type(self, connection):
        return "real"

# manage.py inspectdb

class job_data(models.Model):
    jid = models.CharField(primary_key = True, max_length=32)
    submit_time = models.DateTimeField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    runtime = models.FloatField(blank=True, null=True)
    timelimit = models.FloatField(blank=True, null=True)
    node_hrs = models.FloatField(blank=True, null=True)
    nhosts = models.IntegerField(blank=True, null=True)
    ncores = models.IntegerField(blank=True, null=True)
    username = models.CharField(max_length=64)
    account = models.CharField(max_length=64, blank=True, null=True)
    queue = models.CharField(max_length=64, blank=True, null=True)
    state = models.CharField(max_length=64, blank=True, null=True)
    QOS = models.CharField(max_length=64, blank=True, null=True)
    jobname = models.TextField(blank=True, null=True)
    host_list   = ArrayField(models.TextField())

    class Meta:
        db_table = 'job_data'
        managed = True
    
    def __unicode__(self):
        return str(self.id)

    def color(self):
        if self.state == 'COMPLETED': 
            ret_val = "E1EDFA"
        elif self.state == 'FAILED':
            ret_val = "FFB2B2"
        else:
            ret_val = "silver"
        return ret_val

class metrics_data(models.Model):
    jid = models.ForeignKey(job_data, on_delete = models.CASCADE, db_column='jid', blank=True, null=True)
    type = models.CharField(max_length=32, blank=True, null=True)
    metric = models.CharField(max_length=32, blank=True, null=True)
    units = models.CharField(max_length=16, blank=True, null=True)
    value = models.FloatField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'metrics_data'
        unique_together = (('jid', 'type', 'metric'),)

    def __unicode__(self):
        return str(self.jid + '_' + type  + '_' + metric)

#Old Table SQL
"""
    query_create_hostdata_table = CREATE TABLE IF NOT EXISTS host_data (
                                               time  TIMESTAMPTZ NOT NULL,
                                               host  VARCHAR(64),
                                               jid   VARCHAR(32),
                                               type  VARCHAR(32),
                                               dev   VARCHAR(64),
                                               event VARCHAR(64),
                                               unit  VARCHAR(16),
                                               value real,
                                               delta real,
                                               arc   real,
                                               UNIQUE (time, host, type, event)
                                               );

                                          CREATE INDEX ON host_data (host, time DESC);
                                          CREATE INDEX ON host_data (jid, time DESC);

    SELECT create_hypertable('host_data', by_range('time', 86400000000));
    query_create_compression = ALTER TABLE host_data SET \
                                  (timescaledb.compress, timescaledb.compress_orderby = 'time DESC', timescaledb.compress_segmentby = 'host,jid,type,event');
                                  SELECT add_compression_policy('host_data', INTERVAL '12h', if_not_exists => true);


    query_create_process_table = CREATE TABLE IF NOT EXISTS proc_data (
    jid         VARCHAR(32) NOT NULL,
    host        VARCHAR(64),
    proc        VARCHAR(512),
    UNIQUE(jid, host, proc)
    );

    query_create_process_index = "CREATE INDEX ON proc_data (jid);"
"""

# TODO: Compression in migration.py

class host_data(models.Model):
    time = models.DateTimeField(primary_key=True)
    host = models.CharField(max_length=64, blank=True, null=True)
    jid = models.CharField(max_length=32, blank=True, null=True)
    type = models.CharField(max_length=32, blank=True, null=True)
    dev = models.CharField(max_length=64, blank=True, null=True)
    event = models.CharField(max_length=64, blank=True, null=True)
    unit = models.CharField(max_length=16, blank=True, null=True)
    value = RealField(null=True)
    arc = RealField(null=True)
    delta = RealField(null=True)

    class Meta:
        db_table = 'host_data'
        unique_together = (('time', 'host', 'type', 'event'),)
        indexes = [
            models.Index(fields=["host", "time"]),
            models.Index(fields=["jid", "time"]),
        ]

class proc_data(models.Model):
    jid = models.CharField(max_length=32, blank=True, null=True)
    host = models.CharField(max_length=64, blank=True, null=True)
    proc = models.CharField(max_length=512, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'proc_data'
        unique_together = (('jid', 'host', 'proc'),)
        indexes = [
            models.Index(fields=["jid"]),
        ]

    def __unicode__(self):
        return str(self.id)

hpcperfstats/site/machine/views.py
import sys
import traceback
# Append your local repository path here:
# sys.path.append("/home/sg99/hpcperfstats")
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from django.db.models import Q, F, FloatField, ExpressionWrapper
from django.core.cache import cache
from django.db.models.functions import Cast 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django import forms
from django.shortcuts import get_object_or_404
from django.contrib import messages
from cryptography.fernet import Fernet
from django.http import HttpRequest

import os,pwd

from hpcperfstats.analysis.metrics import metrics
from hpcperfstats.analysis.gen import jid_table
from hpcperfstats.site.machine.models import job_data, metrics_data
from hpcperfstats.site.xalt.models import run, join_run_object, lib
import hpcperfstats.conf_parser as cfg
import hpcperfstats.analysis.plot as plots

#xalt
from hpcperfstats.site.xalt.models import run, join_run_object, lib

from datetime import datetime, timedelta

from numpy import array, histogram, log, linspace, isnan
from math import ceil

from bokeh.embed import components
from bokeh.layouts import gridplot
from bokeh.plotting import figure
from bokeh.models import HoverTool
import time
#try:
#from hpcperfstats.site.machine.agave_auth import check_for_tokens
#except:
#pass

import psycopg2
from pandas import DataFrame, to_timedelta
from hpcperfstats.analysis.gen.utils import read_sql, clean_dataframe

class DataNotFoundException(Exception):
    pass

class libset_c: 
     def __init__(self,object_path,module_name):
         self.module_name=module_name
         self.object_path=object_path
class xalt_data_c:
     def __init__(self): 
         self.exec_path=[]
         self.cwd=[]
         self.libset=[]
          

CONNECTION = cfg.get_db_connection_string()

def home(request, error = False):
    field = {}
    month_dict ={}
    date_list = DataFrame(job_data.objects.values("end_time"))["end_time"].dt.date.drop_duplicates()
    print(date_list)
    
    for date in date_list.sort_values():
        y, m, d = str(date.year), str(date.month), str(date.day)
        month_dict.setdefault(y + '-' + m, [])
        month_dict[y + '-' + m].append((str(date), d))

    field["machine_name"] = cfg.get_host_name_ext()
    field['date_list'] = sorted(month_dict.items())[::-1]
    field['error'] = error

    field['metrics'] = metrics_data.objects.distinct("metric").values("metric", "units")


    field["choice"] = ChoiceForm()
    return render(request, "machine/search.html", field)

def search(request):

    if 'jid' in request.GET:
        try:
            job_objects = job_data.objects            
            job = job_objects.get(jid = request.GET['jid'])
            return HttpResponseRedirect("/machine/job/"+str(job.jid)+"/")
        except:
            messages.error(request, "No result found in search")
            pass
    elif 'host' in request.GET and request.GET["host"]:
        try: 
            print("try to get host")
            return host_detail(request)
        except:
            messages.error(request, "No result found in search")
            pass
    else:
        try:
           return index(request)
        except:
            messages.error(request, "No result found in search")
            pass

    return home(request, error = True)
    

def index(request, **kwargs):

    fields = request.GET.dict()    
    fields = { k:v for k, v in fields.items() if v }
    fields.update(kwargs)
    print(fields)

    ### Filter 
    # Build query and filter on job accounting data
    acct_data = { k:v for k,v in fields.items() if k.split('_', 1)[0] != "metrics" and k != "page" }
    job_list = job_data.objects.filter(**acct_data).order_by('-end_time')

    # Build query and filter iteratively on derived metrics data
    df_fields = []
    metrics = { k.split('_',1)[1]:v for k,v in fields.items() if k.split('_', 1)[0] == "metrics" }
    for key, val in metrics.items():
        name, op = key.split('__')
        mquery = { "metrics_data__metric" : name, "metrics_data__value__" + op : val }
        job_list = job_list.filter(**mquery)
        df_fields += [ name ]
    fields['nj'] = job_list.count()
    df_fields = list(set(df_fields))
    
    # Build dataframe for derived metrics for histograms
    metric_dict = {}
    jid_dict = { "jid" : [] }
    hist_metrics = []
    if not len(job_list):
        raise DataNotFoundException("No data found for this search request")
    for job in job_list:
        jid_dict["jid"] += [ job.jid ]
        for name in df_fields:
            metric_set = job.metrics_data_set.all().filter(metric = name) 
            hist_metrics += [(name, metric_set[0].units)]
            for m in metric_set:
                metric_dict.setdefault(m.metric, [])
                metric_dict[m.metric] += [ m.value ]
    jid_dict.update(metric_dict)
    df = DataFrame(jid_dict)
    df = df.set_index("jid")
    hist_metrics = list(set(hist_metrics))
    
    # Build job accounting data columns of dataframe for histograms
    df_fields = ["jid", "start_time", "submit_time", "runtime", "nhosts"]
    df = df.join(DataFrame(job_list.values(*df_fields)).set_index("jid"))

    # Base fields to use in histograms added to derived metrics explicitly searched on
    hist_metrics += [("runtime", "hours"), ("nhosts", "#nodes"), ("queue_wait", "hours")]
    df["queue_wait"] = to_timedelta(df["start_time"] - df["submit_time"]).dt.total_seconds()/3600
    df["runtime"] = df["runtime"]/3600.

    df = clean_dataframe(df)

    ###

    ### Pagination
    paginator = Paginator(job_list, min(100, len(job_list)))
    page_num = request.GET.get('page')

    try:
        jobs = paginator.page(page_num)
    except PageNotAnInteger:
        jobs = paginator.page(1)
    except EmptyPage:
        jobs = paginator.page(paginator.num_pages)

    fields['job_list'] = jobs
    ###

    ### Build Histogram Plots    
    plots = []
    for metric, label in hist_metrics:
        plots += [job_hist(df, metric, label)]        
    fields["script"], fields["div"] = components(gridplot(plots, ncols = 2))
    ###

    fields['logged_in'] = True
    if '?' in request.get_full_path():
        fields['current_path'] = request.get_full_path()
        
    return render(request, "machine/index.html", fields)

# Generate Histogram Plots of a List of Metrics    
def job_hist(df, metric, label):
    hover = HoverTool(tooltips = [ ("jobs", "@top"), ("bin", "[@left, @right]") ], point_policy = "snap_to_data")
    TOOLS = ["pan,wheel_zoom,box_zoom,reset,save,box_select", hover]

    values = list(df[metric].values)
    if len(values) == 0: return None

    hist, edges = histogram(values, bins = linspace(0, max(values), max(3, int(5*log(len(values))))))

    plot = figure(title = metric, toolbar_location = None, plot_height = 400, plot_width = 600, 
                  y_range = (1, max(hist)), tools = TOOLS) #  y_axis_type = "log",
    plot.xaxis.axis_label = label
    plot.yaxis.axis_label = "# jobs"

    plot.quad(top = hist, bottom = 1, left = edges[:-1], right = edges[1:])    

    return plot

def heat_map(pk):    
    data = get_data(pk)
    hm = plots.HeatMap()
    return components(hm.plot(data))

class job_dataDetailView(DetailView):
    model = job_data

    def get_queryset(self):
        queryset = super(job_dataDetailView, self).get_queryset()
        return queryset
        """
        if "is_staff" in self.request.session and self.request.session["is_staff"]:
            return queryset
        return queryset.filter(user = self.request.session["username"])
        """
    def get(self, request, *args, **kwargs):
        """
        if not check_for_tokens(self.request):
            return HttpResponseRedirect("/login_prompt")
        """
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):

        context = super(job_dataDetailView, self).get_context_data(**kwargs)
        job = context['job_data']
        
        j = jid_table.jid_table(job.jid)

        context["host_list"] = j.acct_host_list




# gpu
        try:
          gpu_data = read_sql("""select type,event,value from host_data where jid = '{0}' and type='nvidia_gpu' and event='utilization'""".format(job.jid), conj)
          gpu_data = gpu_data.iloc[1:-1]
          gpu_utilization_max = gpu_data['value'].max()
          gpu_utilization_mean = gpu_data['value'].mean()
          if not isnan(gpu_utilization_max):
            context["gpu_active"]=ceil(gpu_utilization_max/100.0)
            context["gpu_utilization_max"]=gpu_utilization_max
            context["gpu_utilization_mean"]=gpu_utilization_mean
        except:
          print("error getting gpu data")

# xalt
        if not cfg.get_xalt_user() == '':
          xalt_data=xalt_data_c()
          for r in run.objects.using('xalt').filter(job_id = job.jid):
            if "usr" in r.exec_path.split('/'): continue
            xalt_data.exec_path.append(r.exec_path)
            xalt_data.cwd.append(r.cwd[0:128])
            for join in join_run_object.objects.using('xalt').filter(run_id = r.run_id):
              object_path = lib.objects.using('xalt').get(obj_id = join.obj_id).object_path
              module_name = lib.objects.using('xalt').get(obj_id = join.obj_id).module_name
              if not module_name: module_name = 'none'
              if any(libtmp.module_name == module_name for libtmp in xalt_data.libset): continue
              xalt_data.libset.append (libset_c(object_path = object_path, module_name = module_name))
          xalt_data.exec_path=list(set(xalt_data.exec_path))
          xalt_data.cwd=list(set(xalt_data.cwd))
          xalt_data.libset=sorted(xalt_data.libset, key=lambda x:x.module_name)
          context['xalt_data'] = xalt_data
        else:
          xalt_data = []



        # Build Summary Plot

hpcperfstats/site/machine/templates/machine/index.html
{% extends "hpcperfstats_site/base.html" %}
{% block content %}

<h4>{{ qname }}</h4>
<center>
  {{ script|safe }}
  {{ div|safe }}
</center>

<hr>

<h4>Flagged Jobs:</h4>
<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#flagged">Click for Flagged Jobs</button>
<div id="flagged" class="collapse">
<div class="table-responsive">
<!---
  <table class="table table-condensed" style="max-width=100%;">
    {% if md_job_list %}

    <tr>
      <th>Top metadata request rates (B)</th>
    </tr>
    {% for key,values in md_job_list.items %} 
    <tr><td><a href="{% url 'machine:user_view' key %}"> {{ key }}</a> </td>
      {% for v,d in values %} 
      <td><a href="{% url 'machine:job_data' v %}">{{ v }}</a>({{ d|stringformat:"0.1f" }})</td>
      {% endfor %}
    </tr>
    {% endfor %}

    {% endif %}


    {% if gigebw_job_list %}

    <tr>
      <th>GigE BW > {{ gigebw_thresh|stringformat:"0.3e" }} MB</th>
    </tr>
    {% for key,values in gigebw_job_list.items %} 
    <tr><td><a href="{% url 'machine:user_view' key %}"> {{ key }}</a> </td>
      {% for v,d in values %} 
      <td><a href="{% url 'machine:job_data' v %}">{{ v }}</a>({{ d|stringformat:"0.3e" }})</td>
      {% endfor %}
    </tr>
    {% endfor %}

    {% endif %}

    {% if idle_job_list %}

    <tr>
      <th>Node Imbalance</th>
    </tr>
    {% for key,values in idle_job_list.items %} 
    <tr><td><a href="{% url 'machine:user_view'  key %}"> {{ key }}</a></td>
      {% for v,d in values %} 
      <td><a href="{% url 'machine:job_data'  v %}">{{ v }}</a>({{ d }})</td>
      {% endfor %}
    </tr>
    {% endfor %}

    {% endif %}

    
    {% if cat_job_list %}

    <tr>
      <th>Time Imbalance</th>
    </tr>
    {% for key,values in cat_job_list.items %} 
    <tr><td><a href="{% url 'machine:user_view'  key %}"> {{ key }}</a> </td>
      {% for v,d in values %} 
      <td><a href="{% url 'machine:job_data'  v %}">{{ v }}</a>({{ d }})</td>
      {% endfor %}
    </tr>
    {% endfor %}

    {% endif %}

    
    {% if cpi_job_list %}

    <tr>
      <th>High CPI ({{cpi_thresh}}, %{{cpi_per|stringformat:"0.1f"}})</th>
    </tr>
    {% for key,values in cpi_job_list.items %} 
    <tr><td><a href="{% url 'machine:user_view' key %}">{{ key }}</a></td>
      {% for v,d in values %} 
      <td><a href="{% url 'machine:job_data' v %}">{{ v }}</a>({{ d|stringformat:"0.1f" }})</td>
      {% endfor %}
    </tr>
    {% endfor %}

    {% endif %}
  </table>
--->
</div>
</div>



{% if date %}
<h3>List of Jobs run on {{ date }}</h3>
{% endif %}
<h4> #Jobs = {{ nj }} </h4>

    {% if job_list.has_other_pages %}
    <div class="pagination">
      {% if job_list.has_previous %}

      {% if current_path %}
      <li><a href="{{ current_path }}&page={{ job_list.previous_page_number }}">&laquo;</a></li>
      {% else %}
      <li><a href="?page={{ job_list.previous_page_number }}">&laquo;</a></li>
      {% endif %}

      {% else %}
      <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in job_list.paginator.page_range %}
      {% if job_list.number == i %}
      <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}

      {% if current_path %}
      <li><a href="{{ current_path }}&page={{ i }}">{{ i }}</a></li>
      {% else %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}

      {% endif %}
      {% endfor %}
      {% if job_list.has_next %}

      {% if current_path %}
      <li><a href="{{ current_path }}&page={{ job_list.next_page_number }}">&raquo;</a></li>
      {% else %}
      <li><a href="?page={{ job_list.next_page_number }}">&raquo;</a></li>
      {% endif %}

      {% else %}
      <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </div>
    {% endif %}

    <table class="table table-condensed table-bordered">
      <thead>
        <tr>
	  <th> Job ID </th>
	  <th> Data   </th>
	  <th> user </th>
	  <th> Account </th>
	  <th> start time </th>
	  <th> end time </th>
	  <th> run time (s)</th>
	  <th> queue </th>
	  <th> name </th>
	  <th> status </th>
	  <th> cores </th>
	  <th> nodes</th>
	  <th> node hrs </th>
	</tr>
      </thead>
      <tbody>
      {% for job in job_list %}
        <tr bgcolor="{{job.color}}">
          <td><a href="{% url 'machine:job_data' job.jid %}">{{ job.jid }}</a>

	  {% if job.metrics_data_set.all %}
          <td>True</td> 
	  {% else %} <td align=right> False </td> 
	  {% endif %}

	  {% if job.username %}
          <td><a href="{% url 'machine:username_view' job.username %}" >{{ job.username }}</td> 
	  {% else %} <td align=right> unknown </td> 
	  {% endif %}
	  
	  {% if job.account %}
          <td align=right><a href="{% url 'machine:account_view' job.account %}" >{{ job.account }}</td>
	  {% else %} <td align=right> None </td>
	  {% endif %}

          <td align=right>{{ job.start_time }}</td>
          <td align=right>{{ job.end_time }}</td>
          <td align=right>{{ job.runtime }}</td>
          <td align=right>{{ job.queue }}</td>
          <td align=right>{{ job.jobname }}</td>
          <td align=right>{{ job.state }}</td>
          <td align=right>{{ job.ncores }}</td>
          <td align=right>{{ job.nhosts }}</td>
	  <td align=right>{{ job.node_hrs|stringformat:".2f" }} </td>
        </tr>
	{% endfor %}
      </tbody> 
    </table>

{% endblock %}

hpcperfstats/site/machine/templates/machine/proc_detail.html
{% extends "hpcperfstats_site/base.html" %}
{% block content %}

<h2>{{ proc_name }}</h2>

<table class="table table-condensed table-bordered">
  <thead><th>host</th><th>proc/pid</th><th>VMem HWM ({{ hwm_unit }})</th><th>ResMem HWM ({{ hwm_unit }})</th><th>Affinity</th><th>Threads</th></thead>
  <tbody>
    {% for host, procs in host_map.items %}
    {% for proc, vals in procs.items %} 
    <tr>
      <td>{{ host }}</td><td>{{ proc }}</td>
      {% for val in vals %} 
      <td>{{ val }}</td>
      {% endfor %}
      {% endfor %}
      </tr>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

hpcperfstats/site/machine/templates/machine/type_detail.html
{% extends "hpcperfstats_site/base.html" %}
{% block content %}

<div class="container-fluid">
    <h2>Job {{ jobid }} / Type {{ type_name }}</h2>
    <h4>Rates Aggregated over devices</h4>
    <div class="graphs">
      {{ tscript|safe }}
      {{ tdiv|safe }}
    </div>
{% if stats_data %}
<h4>Counts Aggregated over devices and hosts</h4>
<div class="table-responsive">
  <table class="table table-condensed table-bordered" style="max-width:100%;">
    <thead>
      <tr><th>record</th>{% for key in schema %} <th>{{key}}</th>{% endfor %}</tr>
    </thead>
    <tbody>
      {% for time, values in stats_data %}
      <tr><th>{{time}}</th>{% for value in values %}<th>{{ value|stringformat:"0.2e" }} </th> {% endfor %}</tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<!-- 
 <h1>Type not found</h1>
-->
<h1>...</h1>
{% endif %}
</div>

{% endblock %}