tacc_stats_web/apps/tacc_stats/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import DetailView, ListView
from tacc_stats.models import Job
from tacc_stats.views import index, job_memused_hist, job_timespent_hist, create_heatmap, search, JobListView, render_json, get_job, data, list_hosts

urlpatterns = patterns('',
    url(r'^$', index),
    url(r'^joblist$',
        JobListView.as_view()),
    url(r'^job/(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Job,
        #    template_name='tacc_stats/detail.html',
        )),
    url(r'^job_memused_hist$', job_memused_hist ),
    url(r'^job_timespent_hist$', job_timespent_hist ),
    url(r'^job_mem_heatmap/(\d+)/$', create_heatmap, {'trait' : 'memory'}),
    url(r'^job_files_opened_heatmap/(\d+)/$', create_heatmap, {'trait' : 'files'}),
    url(r'^job_flops_heatmap/(\d+)/$', create_heatmap, {'trait' : 'flops'}),
    url(r'^search/$', search ),
    url(r'^render/jobs/$', render_json),
    url(r'^(\w+)/(\d+)/$', get_job ),
    url(r'^data/$', data ),
    url(r'^hosts/$', list_hosts ),
)

tacc_stats_web/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'webapp.views.home', name='home'),
    url(r'^tacc_stats/', include('tacc_stats.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

tacc_stats_web/apps/tacc_stats/models.py
"""The database models of tacc stats"""

from django.db import models
import time
import math

COLORS = { 
    'Normal' : "background-color: rgba(0%, 0%, 100%, .2);",
    'High Files Open' : "background-color: rgba(100%, 0%, 0%, .2);",
    'High Memory Used' : "background-color: rgba(80%, 30%, 0%, .2)",
    'High Runtime' : "background-color: rgba(0%, 100%, 0%, .2)",
    'High Idle' : "background-color: rgba(50%, 0%, 50%, .2)"
}

class System(models.Model):
    """Details about the cluster"""
    name = models.CharField(max_length=128)

    def __unicode__(self):
        return self.name

class Node(models.Model):
    """Details about the specific node run on """
    name = models.CharField(max_length=128)
    system = models.ForeignKey(System)

    def __unicode__(self):
        return "%s.%s" % (self.name, self.system.name)

class User(models.Model):
    """ The person who submitted the job to the queue """
    user_name = models.CharField(max_length=128)
    systems = models.ManyToManyField(System)

    def __str__(self):
        return self.user_name

    def __unicode__(self):
        return "User(%s)" % self.user_name

class Job(models.Model):
    """
    Details about the task submitted to the compute cluster
    """
    system = models.ForeignKey(System)
    acct_id = models.BigIntegerField()
    owner = models.ForeignKey(User, null=True)
    hosts = models.ManyToManyField(Node)
    queue = models.CharField(max_length=16, null=True)
    queue_wait_time = models.IntegerField(null=True)
    begin = models.PositiveIntegerField(null=True)
    end = models.PositiveIntegerField(null=True)
    #run_time = models.IntegerField(null=True)
    #nr_hosts = models.IntegerField(null=True)
    nr_bad_hosts = models.IntegerField(null=True)
    nr_slots = models.IntegerField(null=True)
    pe = models.CharField(max_length=8, null=True)
    failed = models.BooleanField()
    exit_status = models.IntegerField(null=True)

    amd64_pmc_CTL0 = models.BigIntegerField(null=True)
    amd64_pmc_CTL1 = models.BigIntegerField(null=True)
    amd64_pmc_CTL2 = models.BigIntegerField(null=True)
    amd64_pmc_CTL3 = models.BigIntegerField(null=True)
    amd64_pmc_CTR0 = models.BigIntegerField(null=True)
    amd64_pmc_CTR1 = models.BigIntegerField(null=True)
    amd64_pmc_CTR2 = models.BigIntegerField(null=True)
    amd64_pmc_CTR3 = models.BigIntegerField(null=True)
    block_in_flight = models.BigIntegerField(null=True)
    block_io_ticks = models.BigIntegerField(null=True)
    block_rd_ios = models.BigIntegerField(null=True)
    block_rd_merges = models.BigIntegerField(null=True)
    block_rd_sectors = models.BigIntegerField(null=True)
    block_rd_ticks = models.BigIntegerField(null=True)
    block_time_in_queue = models.BigIntegerField(null=True)
    block_wr_ios = models.BigIntegerField(null=True)
    block_wr_merges = models.BigIntegerField(null=True)
    block_wr_sectors = models.BigIntegerField(null=True)
    block_wr_ticks = models.BigIntegerField(null=True)
    cpu_idle = models.BigIntegerField(null=True)
    cpu_iowait = models.BigIntegerField(null=True)
    cpu_irq = models.BigIntegerField(null=True)
    cpu_nice = models.BigIntegerField(null=True)
    cpu_softirq = models.BigIntegerField(null=True)
    cpu_system = models.BigIntegerField(null=True)
    cpu_user = models.BigIntegerField(null=True)
    ib_sw_rx_bytes = models.BigIntegerField(null=True)
    ib_sw_rx_packets = models.BigIntegerField(null=True)
    ib_sw_tx_bytes = models.BigIntegerField(null=True)
    ib_sw_tx_packets = models.BigIntegerField(null=True)
    llite_alloc_inode_scratch = models.BigIntegerField(null=True)
    llite_alloc_inode_share = models.BigIntegerField(null=True)
    llite_alloc_inode_work = models.BigIntegerField(null=True)
    llite_close_scratch = models.BigIntegerField(null=True)
    llite_close_share = models.BigIntegerField(null=True)
    llite_close_work = models.BigIntegerField(null=True)
    llite_direct_read_scratch = models.BigIntegerField(null=True)
    llite_direct_read_share = models.BigIntegerField(null=True)
    llite_direct_read_work = models.BigIntegerField(null=True)
    llite_direct_write_scratch = models.BigIntegerField(null=True)
    llite_direct_write_share = models.BigIntegerField(null=True)
    llite_direct_write_work = models.BigIntegerField(null=True)
    llite_dirty_pages_hits_scratch = models.BigIntegerField(null=True)
    llite_dirty_pages_hits_share = models.BigIntegerField(null=True)
    llite_dirty_pages_hits_work = models.BigIntegerField(null=True)
    llite_dirty_pages_misses_scratch = models.BigIntegerField(null=True)
    llite_dirty_pages_misses_share = models.BigIntegerField(null=True)
    llite_dirty_pages_misses_work = models.BigIntegerField(null=True)
    llite_flock_scratch = models.BigIntegerField(null=True)
    llite_flock_share = models.BigIntegerField(null=True)
    llite_flock_work = models.BigIntegerField(null=True)
    llite_fsync_scratch = models.BigIntegerField(null=True)
    llite_fsync_share = models.BigIntegerField(null=True)
    llite_fsync_work = models.BigIntegerField(null=True)
    llite_getattr_scratch = models.BigIntegerField(null=True)
    llite_getattr_share = models.BigIntegerField(null=True)
    llite_getattr_work = models.BigIntegerField(null=True)
    llite_getxattr_scratch = models.BigIntegerField(null=True)
    llite_getxattr_share = models.BigIntegerField(null=True)
    llite_getxattr_work = models.BigIntegerField(null=True)
    llite_inode_permission_scratch = models.BigIntegerField(null=True)
    llite_inode_permission_share = models.BigIntegerField(null=True)
    llite_inode_permission_work = models.BigIntegerField(null=True)
    llite_ioctl_scratch = models.BigIntegerField(null=True)
    llite_ioctl_share = models.BigIntegerField(null=True)
    llite_ioctl_work = models.BigIntegerField(null=True)
    llite_listxattr_scratch = models.BigIntegerField(null=True)
    llite_listxattr_share = models.BigIntegerField(null=True)
    llite_listxattr_work = models.BigIntegerField(null=True)
    llite_mmap_scratch = models.BigIntegerField(null=True)
    llite_mmap_share = models.BigIntegerField(null=True)
    llite_mmap_work = models.BigIntegerField(null=True)
    llite_open_scratch = models.BigIntegerField(null=True)
    llite_open_share = models.BigIntegerField(null=True)
    llite_open_work = models.BigIntegerField(null=True)
    llite_read_bytes_scratch = models.BigIntegerField(null=True)
    llite_read_bytes_share = models.BigIntegerField(null=True)
    llite_read_bytes_work = models.BigIntegerField(null=True)
    llite_removexattr_scratch = models.BigIntegerField(null=True)
    llite_removexattr_share = models.BigIntegerField(null=True)
    llite_removexattr_work = models.BigIntegerField(null=True)
    llite_seek_scratch = models.BigIntegerField(null=True)
    llite_seek_share = models.BigIntegerField(null=True)
    llite_seek_work = models.BigIntegerField(null=True)
    llite_setattr_scratch = models.BigIntegerField(null=True)
    llite_setattr_share = models.BigIntegerField(null=True)
    llite_setattr_work = models.BigIntegerField(null=True)
    llite_setxattr_scratch = models.BigIntegerField(null=True)
    llite_setxattr_share = models.BigIntegerField(null=True)
    llite_setxattr_work = models.BigIntegerField(null=True)
    llite_statfs_scratch = models.BigIntegerField(null=True)
    llite_statfs_share = models.BigIntegerField(null=True)
    llite_statfs_work = models.BigIntegerField(null=True)
    llite_truncate_scratch = models.BigIntegerField(null=True)
    llite_truncate_share = models.BigIntegerField(null=True)
    llite_truncate_work = models.BigIntegerField(null=True)
    llite_write_bytes_scratch = models.BigIntegerField(null=True)
    llite_write_bytes_share = models.BigIntegerField(null=True)
    llite_write_bytes_work = models.BigIntegerField(null=True)
    lnet_rx_bytes_dropped = models.BigIntegerField(null=True)
    lnet_rx_bytes = models.BigIntegerField(null=True)
    lnet_rx_msgs_dropped = models.BigIntegerField(null=True)
    lnet_rx_msgs = models.BigIntegerField(null=True)
    lnet_tx_bytes = models.BigIntegerField(null=True)
    lnet_tx_msgs = models.BigIntegerField(null=True)
    mem_Active = models.BigIntegerField(null=True)
    mem_AnonPages = models.BigIntegerField(null=True)
    mem_Bounce = models.BigIntegerField(null=True)
    mem_Dirty = models.BigIntegerField(null=True)
    mem_FilePages = models.BigIntegerField(null=True)
    mem_HugePages_Free = models.BigIntegerField(null=True)
    mem_HugePages_Total = models.BigIntegerField(null=True)
    mem_Inactive = models.BigIntegerField(null=True)
    mem_Mapped = models.BigIntegerField(null=True)
    mem_MemFree = models.BigIntegerField(null=True)
    mem_MemTotal = models.BigIntegerField(null=True)
    mem_MemUsed = models.BigIntegerField(null=True)
    mem_NFS_Unstable = models.BigIntegerField(null=True)
    mem_PageTables = models.BigIntegerField(null=True)
    mem_Slab = models.BigIntegerField(null=True)
    mem_Writeback = models.BigIntegerField(null=True)
    net_collisions = models.BigIntegerField(null=True)
    net_multicast = models.BigIntegerField(null=True)
    net_rx_bytes = models.BigIntegerField(null=True)
    net_rx_compressed = models.BigIntegerField(null=True)
    net_rx_crc_errors = models.BigIntegerField(null=True)
    net_rx_dropped = models.BigIntegerField(null=True)
    net_rx_errors = models.BigIntegerField(null=True)
    net_rx_fifo_errors = models.BigIntegerField(null=True)
    net_rx_frame_errors = models.BigIntegerField(null=True)
    net_rx_length_errors = models.BigIntegerField(null=True)
    net_rx_missed_errors = models.BigIntegerField(null=True)
    net_rx_over_errors = models.BigIntegerField(null=True)
    net_rx_packets = models.BigIntegerField(null=True)
    net_tx_aborted_errors = models.BigIntegerField(null=True)
    net_tx_bytes = models.BigIntegerField(null=True)
    net_tx_carrier_errors = models.BigIntegerField(null=True)

tacc_stats_web/apps/tacc_stats/forms.py
from django import forms
from django.forms import ModelForm
from models import Job

class SearchForm(ModelForm):
    begin = forms.DateTimeField()
    end = forms.DateTimeField()

    class Meta:
        model = Job
        fields = ('owner', 'begin', 'end', 'acct_id')
#        widgets = {
#            'begin': forms.DateTimeField(),
#        }

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = False

tacc_stats_web/templates/tacc_stats/index.html
<html>
<head>
    <title>TACC Stats Web</title>
</head>
<body>
<h1>TACC Stats Web Home</h1>
<a href="search">jobsearch</a>

<h2> Charts at a glance </h2>

<img src="job_timespent_hist" alt="Histogram of jobs" />
<img src="job_memused_hist" alt="Histogram of jobs" />

{% if job_list %}
    <h1>Recent problem jobs</h1>
    <table border="1" cellpadding="5">
        <tr><th> ID </th><th> owner </th><th> time spent </th><th> memory used
        </th><th> work open </th><th> irq </th></tr>
    {% for job in job_list %}
        <tr style="{{job.color}}">
            <td><a href="job/{{ job.id }}/">{{ job.acct_id }}</a>
            <td>{{ job.owner }}</td>
            <td align=right>{{ job.runtime }}</td>
            <td align=right>{{ job.mem_MemUsed }}</td>
            <td align=right>{{ job.llite_open_work }}</td>
            <td align=right>{{ job.cpu_irq }}</td>
        </tr>
    {% endfor %}
    </ul>
{% else %}
    <p>No jobs are available.</p>
{% endif %}
</body>
</html>

tacc_stats_web/templates/tacc_stats/job_list.html
<html>
<head>
    <title>TACC Stats Web: Job list</title>
</head>
<body>
{% if job_list %}
    <table border="1" cellpadding="5">
        <tr><th> name </th><th> owner </th><th> hosts </th>
	<th> time spent </th><th> begin </th><th> memory used </th>
	<th> work open </th><th> irq </th></tr>
    {% for job in job_list %}
        <tr style="{{job.color}}">
            <td><a href="/{{ job.pe }}/{{ job.acct_id }}/">{{ job.acct_id }}</a>
            <td>{{ job.owner }}</td>
            <td align=right>{{ job.nr_hosts }}</td>
            <td align=right>{{ job.timespent }}</td>
            <td align=right>{{ job.start_time }}</td>
            <td align=right>{{ job.mem_MemUsed }}</td>
            <td align=right>{{ job.llite_open_work }}</td>
            <td align=right>{{ job.cpu_irq }}</td>
        </tr>
    {% endfor %}
    </ul>
{% else %}
    <p>No jobs are available.</p>
{% endif %}
</body>
</html>

tacc_stats_web/templates/tacc_stats/search.html
<head>
<script src="{{ STATIC_URL }}sorttable.js"></script>
<style type="text/css">
<!--
@import url("{{ STATIC_URL }}style.css");
-->
</style>
<title>Job Search Page</title> 
</head>
<div style="width:100%;height:30%">
<div style="float:left;">
<form action="/tacc_stats/search/" method="POST">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <p><input type="submit" value="Submit"></p>
<form>
</div>
<div style="float:right;">
{% if COLORS %}
    <table id="hor-minimalist-a" border ="1" cellpadding="5">
        <tr><th> Color Legend <th></tr>
        {% for key, value in COLORS.items %}
            <tr style="{{value}}">
                <td>{{ key }}</td>
		<td><br></td>
            </tr>
         {% endfor %}
    </table>
{% endif %}
</div>
</div>
<div>
<div style="height:65%;width:90%">
{% if job_list %}
    <table id="box-table-a" border="1" cellpadding="5" class="sortable">
        <tr><th> ID </th><th> owner </th><th> hosts </th>
        <th> time spent </th><th> begin </th><th> memory used </th>
        <th> work open </th><th> irq </th></tr>
    {% for job in job_list %}
        <tr style="{{job.color}}">
            <td height="{{ job.height }}"><a href="/tacc_stats/{{ job.system }}/{{ job.acct_id }}/">{{ job.acct_id }}</a>
            <td>{{ job.get_owner }}</td>
            <td align=right>{{ job.nr_hosts }}</td>
            <td align=right>{{ job.timespent }}</td>
            <td align=right>{{ job.start_time }}</td>
            <td align=right>{{ job.mem_MemUsed }}</td>
            <td align=right>{{ job.llite_open_work }}</td>
            <td align=right>{{ job.cpu_irq }}</td>
        </tr>
    {% endfor %}
    </ul>
{% else %}
    <p>No jobs are available.</p>
{% endif %}
</div>
<div style="height:5%;clear:both;">
{% if pages %}
    [
    {% for i in pages %}
         {% if i == page %}
             <a href="/tacc_stats/search?p={{ i }}{{ query_string }}"><b>{{ i }}</b></a>
         {% else %}
             {% if i == '...' %}
                 {{ i }}
             {% else %}
                 <a href="/tacc_stats/search?p={{ i }}{{ query_string }}">{{ i }}</a> 
             {% endif %}
         {% endif %}
    {% endfor %}
    ]
{% endif %}
</div>
</div>