hpcperfstats/site/hpcperfstats_site/urls.py
from django.conf.urls import include
from django.urls import path
from django.views.static import serve
from hpcperfstats.site.hpcperfstats_site import settings
from django.contrib import admin
from hpcperfstats.site.machine.views import home
from hpcperfstats.site.machine import urls

admin.autodiscover()
urlpatterns = [
    path(r'', home, name="dates"),
    path(r'machine/', include(urls, namespace = "machine"), name = "machine"),
    path(r'media/<path>', serve, {'document_root': settings.MEDIA_ROOT}, name = "media"),                       
]

#try:
#from hpcperfstats.site.machine.agave_auth import login, logout, login_oauth, agave_oauth_callback, login_prompt
#print("starting TACC Stats with agave authentication")
#urlpatterns += [
#    path(r'login/', login_oauth, name='login'),
#path(r'login_prompt', login_prompt, name='login_prompt'),
#    path(r'logout/', logout, name='logout'),
#    path(r'agave_oauth_callback/', agave_oauth_callback, name='agave_oauth_callback')    
#]
#except: 
#    pass

hpcperfstats/site/machine/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import DetailView, ListView
from hpcperfstats.site.machine.models import job_data
from hpcperfstats.site.machine.views import *

app_name = "hpcperfstats"

urlpatterns = [
                       path(r'', home, name='dates'),
                       path(r'job/<pk>/',
                           job_dataDetailView.as_view(), name='job_data'),
                       path(r'host/<host>/', host_detail, name='host_view'),
                       path(r'date/<end_time__date>', index, name='date_view'),
                       path(r'username/<username>/', index, name = 'username_view'),
                       path(r'account/<account>/'  , index, name = 'account_view'),
                       path(r'job/<jid>/<type_name>/', type_detail, name = 'type_detail'),
                       #path(r'proc/<pk>/<proc_name>/', proc_detail, name = 'proc_detail'),
                       #path(r'exe/<exe__icontains>)/', index, name='exe_view'),                       
                       path(r'search/',search, name='search'),
]

hpcperfstats/site/hpcperfstats_site/templates/hpcperfstats_site/base.html
{% load static %}
<html>
  <head>
    <title>TACC Stats</title>
    <link rel="stylesheet" href="https://bootswatch.com/3/spacelab/bootstrap.min.css">
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-2.3.3.min.css" rel="stylesheet" type="text/css">
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-2.3.3.min.css" rel="stylesheet" type="text/css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-2.3.3.min.js"></script>
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-2.3.3.min.js"></script>
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-tables-2.3.3.min.js"></script>
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-gl-2.3.3.min.js"></script>
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-api-2.3.3.min.js"></script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
    .navbar-brand{
        position: absolute;
        width: 100%;
        left: 0;
        text-align: center;
        margin: auto;
    }
    </style>
  </head>

  {% if messages %}
        <div class="messages">
        {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
                        {{ message }}
                </div>
        {% endfor %}
        </div>
  {% endif %}

  <body>
    <div class ="container-fluid">
      <nav class="navbar navbar-default" role="navigation">
	<div class="navbar-header"><a href="https://www.tacc.utexas.edu"> <img src="{% url 'media' path='TACC_logo.png' %}" style="max-width:50%;"/></a></div>
	<center>{{ machine_name }}</center>
	<a>
	  <form class="navbar-form navbar-right" action="{% url 'machine:search' %}" method="get" role="search">
            <div class="form-group">
              <input type="text" class="form-control" name ="jid" placeholder="Job ID">
            </div>
            <button type="submit" class="btn btn-default">find job</button>
	    

	  </form>
	</a>
      </nav>

    {% block content %}
    {% endblock %}
    </div>
  </body>
</html>